# Generated by Django 5.1.2 on 2024-11-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=20)),
                ('price_per_day', models.IntegerField()),
                ('price_per_hour', models.IntegerField()),
                ('image', models.ImageField(upload_to='bike_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('gear_type', models.CharField(max_length=50)),
                ('price_per_day', models.IntegerField()),
                ('price_per_hour', models.IntegerField()),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
        ),
    ]
