# Generated by Django 5.1.2 on 2024-11-08 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.city'),
        ),
        migrations.AddField(
            model_name='bike',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.state'),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.city'),
        ),
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.state'),
        ),
    ]
