# Generated by Django 5.1.2 on 2024-11-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_bike_city_bike_state_car_city_car_state'),
        ('accounts', '0002_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Self Pickup'), ('delivery', 'Delivery')], max_length=50)),
                ('pickup_delivery_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pick_delivery_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('pickup_location', models.CharField(blank=True, max_length=300, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=300, null=True)),
                ('license_image', models.ImageField(upload_to='licenceImage/')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bike')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer_register')),
            ],
        ),
    ]
