# Generated by Django 5.1.2 on 2024-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_cart_bike_alter_cart_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pick_delivery_time',
            new_name='delivery_time',
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
