# Generated by Django 5.1.2 on 2024-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_pick_delivery_time_cart_delivery_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pickup_delivery_date',
            new_name='delivery_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
