# Generated by Django 5.1.2 on 2024-11-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_pickup_delivery_date_cart_delivery_date_and_more'),
        ('accounts', '0002_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='grand_total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='license_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='return_time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.CreateModel(
            name='Rented_vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(blank=True, choices=[('pickup', 'Self Pickup'), ('delivery', 'Delivery')], max_length=50, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=300, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=300, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='licenceImage/')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike_rent', to='App.cart')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_rent', to='App.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer_register')),
            ],
        ),
    ]
