# Generated by Django 5.1.2 on 2024-11-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_cart_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rented_vehicles',
            name='grand_total_price',
        ),
        migrations.AddField(
            model_name='rented_vehicles',
            name='payment_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
