# Generated by Django 5.1.2 on 2024-11-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_rented_vehicles_license_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rented_vehicles',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bike_rent', to='App.bike'),
        ),
        migrations.AlterField(
            model_name='rented_vehicles',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_rent', to='App.car'),
        ),
        migrations.AlterField(
            model_name='rented_vehicles',
            name='license_file',
            field=models.FileField(default=1, upload_to='licenceFile/'),
            preserve_default=False,
        ),
    ]
